print("OPERADOR\tSIGNIFICADO")
print("==\t\tIgual a")
print("!=\t\tDiferente de")
print("<\t\tMenor que")
print(">\t\tMaior que")
print("<=\t\tMenor ou igual a")
print(">=\t\tMaior ou igual a")

print()
print("Exemplo de operações")
print("42 == 42 -> "+str(42==42))
print("42 == 49 -> "+str(42==49))
print("2 != 3 -> "+str(2!=3))
print("2 != 2 -> "+str(2!=2))
print("\'hello\' == \'hello\' -> "+str('hello' == 'hello'))
print("\'Hello\' == \'hello\' -> "+str('Hello' == 'hello'))
print("42 == 42.0 -> "+str(42.0==42))
print("42 > 49 -> "+str(42>49))
