print("OPEADORES")
print("AND")
print("OR")
print("NOT")

print()
print("EXPRESSÃO\t\tRESULTADO")
print("True (and) True\t\t"+str(True and True))
print("True (and) False\t"+str(True and False))
print("False (and) False\t"+str(False and False))
print("True (or) True\t\t"+str(True or True))
print("True (or) False\t\t"+str(True or False))
print("False (or) False\t"+str(False or False))
print("(not) False\t\t"+str(not False))
print("(not) True\t\t"+str(not True))
